server:
  port: 8500

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mariadb://localhost:3306/gateway_auth
    username: root
    password: 12345Ab
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka